# Beispiel zu den linearen Operatoren

In [1]:
import numpy as np

Betrachte lineare Abbildung $A: \mathbb{R}^n \to \mathbb{R}^m$

In [2]:
n=3
m=5

A = np.random.randint(-9,9,size=(m,n))

In [3]:
A

array([[ 6, -6, -2],
       [ 3,  8, -3],
       [ 0, -8,  7],
       [-2, -5, -5],
       [-1, -7,  5]])

## Operatornorm bezüglich der Maximumnorm

In [4]:
# max-Norm
np.linalg.norm(A,np.inf)

15.0

In [5]:
np.sum(np.abs(A), axis=1)

array([14, 14, 15, 12, 13])

## bezüglich der 1-Norm

In [6]:
# max-Norm
np.linalg.norm(A,1)

34.0

In [7]:
np.sum(np.abs(A), axis=0)

array([12, 34, 22])

## bezüglich der 2-Norm

In [8]:
# max-Norm
np.linalg.norm(A,2)

16.608519213899957

In [11]:
np.max(np.linalg.eigvals(A.T@A))**(1/2)

16.60851921389995

In [12]:
np.linalg.norm(A)

20.0

In [13]:
help(np.linalg.norm)

Help on function norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these